[package]
name = "chem-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"
bstr = { version = "1.9.0", default-features = false, features = ["std"] }
c-enum = "0.2.3"
concat-idents = { version = "1.1.5", optional = true }
coordgen = { version = "0.2.2", optional = true }
either = "1.10.0"
fmtastic = "0.2.0"
gcd = { version = "2.3.0", optional = true }
hybridmap = "0.1.1"
itertools = "0.12.1"
lazy_static = { version = "1.4.0", optional = true }
lock_api = "0.4.11"
modular-bitfield = "0.11.2"
num-traits = "0.2.18"
petgraph = "0.6.4"
rand = { version = "0.8.5", optional = true }
smallvec = "2.0.0-alpha.5"
thiserror = "1.0.57"
tracing = "0.1.40"

[dev-dependencies]
clap = { version = "4.5.1", features = ["derive"] }
tracing-subscriber = "0.3.18"

[lib]
crate-type = ["lib", "cdylib"]

[features]
default = ["mol-svg", "rand"]
nightly = ["rand?/nightly", "lock_api/nightly"]

mol-svg = ["coordgen"]
rand = ["dep:rand", "gcd"]

c-ffi = ["concat-idents"]
