[package]
name = "chem-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"
bstr = { version = "1.9.0", default-features = false, features = ["std"] }
c-enum = "0.2.3"
coordgen = { version = "0.2.2", optional = true }
fimg = { version = "0.4.37", optional = true, features = ["text"] }
fmtastic = "0.2.0"
fontdue = { version = "0.7.3", optional = true }
hybridmap = "0.1.1"
image = { version = "0.24.9", optional = true, default-features = false, features = ["png", "jpeg"] }
itertools = "0.12.1"
lazy_static = { version = "1.4.0", optional = true }
modular-bitfield = "0.11.2"
num-traits = "0.2.18"
parking_lot = "0.12.1"
petgraph = "0.6.4"
smallvec = "2.0.0-alpha.3"
thiserror = "1.0.57"

[dev-dependencies]
clap = { version = "4.5.1", features = ["derive"] }

[features]
default = ["mol-fmt"]
mol-fmt = ["mol-svg", "mol-bmp"]
mol-svg = ["coordgen"]
mol-bmp = ["coordgen", "fimg", "image", "lazy_static", "fontdue"]
