[package]
name = "chem-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"
bstr = { version = "1.9.0", default-features = false, features = ["std"] }
c-enum = "0.2.3"
coordgen = { version = "0.2.2", optional = true }
fmtastic = "0.1.0"
modular-bitfield = "0.11.2"
parking_lot = "0.12.1"
petgraph = "0.6.4"
smallbitvec = "2.5.1"
smallvec = "1.13.1"
thiserror = "1.0.56"

[dev-dependencies]
clap = { version = "4.4.18", features = ["derive"] }

[features]
default = ["mol-fmt"]
mol-fmt = ["coordgen"]
