[package]
name = "chem-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"
bstr = { version = "1.9.0", default-features = false, features = ["std"] }
c-enum = "0.2.3"
coordgen = { version = "0.2.2", optional = true }
fimg = { version = "0.4.36", optional = true, features = ["text"] }
fmtastic = "0.1.0"
fontdue = { version = "0.7.3", optional = true }
lazy_static = { version = "1.4.0", optional = true }
modular-bitfield = "0.11.2"
num-traits = "0.2.18"
parking_lot = "0.12.1"
petgraph = "0.6.4"
png = { version = "0.17.13", optional = true }
smallvec = "2.0.0-alpha.3"
thiserror = "1.0.56"

[dev-dependencies]
clap = { version = "4.4.18", features = ["derive"] }

[features]
default = ["mol-fmt"]
mol-fmt = ["coordgen", "fimg", "png", "lazy_static", "fontdue"]
